indicator('test', overlay=true, precision=6, max_lines_count=500, max_bars_back=4900, max_boxes_count=500)
//@version=5

semafor = input(true, 'Test Zigzag', group = "Trend settings", tooltip="")
repaint = "false"
cond = array.new_bool(3)

zigzag(Depth, Deviation, Color1, Color2, Size, Type) =>
    var lw = 1
    var hg = 1
    lw += 1
    hg += 1
    p_lw = -ta.lowestbars(Depth)
    p_hg = -ta.highestbars(Depth)
    lowing = lw == p_lw or low - low[p_lw] > Deviation * syminfo.mintick
    highing = hg == p_hg or high[p_hg] - high > Deviation * syminfo.mintick
    lh = ta.barssince(not highing)
    ll = ta.barssince(not lowing)
    down = lh > ll
    if Depth == 150
        array.set(cond, 0, down)
    else if Depth == 34
        array.set(cond, 1, down)
    else if Depth == 9
        array.set(cond, 2, down)

    lower = low[lw] > low[p_lw]
    higher = high[hg] < high[p_hg]
    if lw != p_lw and (not down[1] or lower)
        lw := p_lw < hg ? p_lw : 0
        lw
    if hg != p_hg and (down[1] or higher)
        hg := p_hg < lw ? p_hg : 0
        hg
    x1 = down ? lw : hg
    y1 = down ? low[lw] : high[hg]
    lb = down ? label.style_label_up : label.style_label_down
    label point = na
    colorSwitch = down ? (down ? Color1 : Color2) : na
    if down != down[1]
        nx = down ? hg : lw
        colorSwitch := down ? Color2 : Color1
        point := label.new(bar_index - nx, down ? high[nx] : low[nx], color=colorSwitch, style=label.style_diamond, size=Size)
        point
    
    down != down[1]

switchLarge = false
switchMedium = false
switchSmall = false

if semafor
    switchLarge := zigzag(150, 24.0, color.rgb(65, 255, 239, 45), color.rgb(255, 71, 230, 45), size.normal, 'Large') or switchLarge
    switchLarge

if semafor
    switchMedium := zigzag(34, 6.0, color.rgb(65, 255, 255, 45), color.rgb(255, 65, 198, 45), size.small, 'Medium') or switchMedium
    switchMedium

if semafor
    switchSmall := zigzag(9, 3.0, color.rgb(62, 255, 207, 45), color.rgb(255, 64, 169, 45), size.tiny, 'Small') or switchSmall
    switchSmall


alertcondition(switchLarge or switchMedium or switchSmall, 'Alert All', 'Alert All')
alertcondition((switchLarge and array.get(cond,0)) or (switchMedium and array.get(cond,1)) or (switchSmall and array.get(cond,0)), 'Alert Red', 'Alert Red')
alertcondition((switchLarge and (not array.get(cond,0))) or (switchMedium and (not array.get(cond,1))) or (switchSmall and (not array.get(cond,0))), 'Alert Blue', 'Alert Blue')