indicator('test', overlay=true, precision=6, max_lines_count=500, max_bars_back=4900, max_boxes_count=500)
//@version=5
semafor = input(true, 'Test Zigzag', group = "Trend settings", tooltip="")
repaint = "false"

gmt=input.string("America/New_York",title="Gmt",options=["America/New_York","America/Los_Angeles","America/Chicago","America/Phoenix","America/Toronto"
     ,"America/Vancouver","America/Argentina/Buenos_Aires","America/El_Salvador","America/Sao_Paulo","America/Bogota"
     ,"Europe/Moscow" ,"Europe/Athens"	 ,"Europe/Berlin","Europe/London"	,"Europe/Madrid"	,"Europe/Paris"	,"Europe/Warsaw"
     ,"Australia/Sydney","Australia/Brisbane","Australia/Adelaide","Australia/ACT"	,"Asia/Almaty"	
     ,"Asia/Ashkhabad", "Asia/Riyadh","Asia/Tokyo"	 ,"Asia/Taipei"	 ,"Asia/Singapore"	 ,"Asia/Shanghai"	 ,"Asia/Seoul"	 ,"Asia/Tehran"	 ,"Asia/Dubai"	 ,"Asia/Kolkata"
     ,"Asia/Hong_Kong" ,"Asia/Bangkok"	,"Pacific/Auckland","Pacific/Chatham","Pacific/Fakaofo"	,"Pacific/Honolulu" ],group="Select Time for Signal",inline="hm")

select_gmt=gmt=="America/New_York"? "GMT-4:00":gmt=="America/Los_Angeles"? "GMT-7:00":gmt=="America/Chicago"? "GMT-5:00":gmt=="America/Phoenix"?"GMT-7:00":
           gmt=="America/Toronto"?"GMT-4:00":gmt=="America/Vancouver"?"GMT-7:00": gmt=="America/Argentina/Buenos_Aires"?"GMT-3:00": gmt=="America/El_Salvador"	?"GMT-6:00":
           gmt=="America/Sao_Paulo"?"GMT-3:00": gmt=="America/Bogota"?"GMT-5:00":gmt=="Europe/Moscow"?"GMT+3:00": gmt=="Europe/Athens"?"GMT+3:00":
           gmt=="Europe/Berlin"	?"GMT+2:00": gmt=="Europe/London"?"GMT+1:00": gmt=="Europe/Madrid"?"GMT+2:00": gmt=="Europe/Paris"?"GMT+2:00":gmt=="Europe/Warsaw"?"GMT+2:00":
           gmt=="Australia/Sydney"?"GMT+11:00":gmt=="Australia/Brisbane"?"GMT+10:00":gmt=="Australia/Adelaide"?"GMT+10:30":gmt=="Australia/ACT"?"GMT+9:30":
           gmt=="Asia/Almaty"?"GMT+6:00":gmt=="Asia/Ashkhabad"?"GMT+5:00":gmt=="Asia/Riyadh"?"GMT+3:00":gmt=="Asia/Tokyo"?"GMT+9:00":gmt=="Asia/Taipei"?"GMT+8:00":gmt=="Asia/Singapore"?"GMT+8:00":
           gmt=="Asia/Shanghai"?"GMT+8:00":gmt=="Asia/Seoul"?"GMT+9:00":gmt=="Asia/Tehran"	?"GMT+3:30":gmt=="Asia/Dubai"	?"GMT+4:00":gmt=="Asia/Kolkata"?"GMT+5:30":
           gmt=="Asia/Hong_Kong"?"GMT+8:00":gmt=="Asia/Bangkok"?"GMT+7:00":gmt=="Pacific/Auckland"?"GMT+13:00":gmt=="Pacific/Chatham"?"GMT+13:45":gmt=="Pacific/Fakaofo"	?"GMT+13:00":
           gmt=="Pacific/Honolulu"?"GMT-10:00": na 

// t_r = time(timeframe.period, "0000-0000", select_gmt)
// time_range = not na(t_r)

formattedTime = str.format_time(time, "yyyy-MM-dd HH:mm", select_gmt)
//label.new(bar_index, high, formattedTime)

zigzag(Depth, Deviation, Color1, Color2, Size, Type) =>
    var lw = 1
    var hg = 1
    lw += 1
    hg += 1
    p_lw = -ta.lowestbars(Depth)
    p_hg = -ta.highestbars(Depth)
    lowing = lw == p_lw or low - low[p_lw] > Deviation * syminfo.mintick
    highing = hg == p_hg or high[p_hg] - high > Deviation * syminfo.mintick
    lh = ta.barssince(not highing)
    ll = ta.barssince(not lowing)
    down = lh > ll
    lower = low[lw] > low[p_lw]
    higher = high[hg] < high[p_hg]
    if lw != p_lw and (not down[1] or lower)
        lw := p_lw < hg ? p_lw : 0
        lw
    if hg != p_hg and (down[1] or higher)
        hg := p_hg < lw ? p_hg : 0
        hg
    x1 = down ? lw : hg
    y1 = down ? low[lw] : high[hg]
    lb = down ? label.style_label_up : label.style_label_down
    label point = na
    colorSwitch = down ? (down ? Color1 : Color2) : na

    dottype = down ? "low" : "high"
    if down != down[1]
        nx = down ? hg : lw
        colorSwitch := down ? Color2 : Color1    
        alert("ALERT; type-" + Type + " Swing " + dottype + ", time-" + formattedTime, alert.freq_once_per_bar_close)    
        point := label.new(bar_index - nx, down ? high[nx] : low[nx], color=colorSwitch, style=label.style_diamond, size=Size)
        point
    [down != down[1], down]
switchLarge = false
downLarge = false
switchMedium = false
downMedium = false
switchSmall = false
downSmall = false
if semafor 
    [swing, down] = zigzag(150, 24.0, color.rgb(65, 255, 239, 45), color.rgb(255, 71, 230, 45), size.normal, 'Large')
    switchLarge := swing or switchLarge
    downLarge := down
if semafor
    [swing, down] = zigzag(34, 6.0, color.rgb(65, 255, 255, 45), color.rgb(255, 65, 198, 45), size.small, 'Medium')
    switchMedium := swing or switchMedium
    downMedium := down
if semafor
    [swing, down] = zigzag(9, 3.0, color.rgb(62, 255, 207, 45), color.rgb(255, 64, 169, 45), size.tiny, 'Small')
    switchSmall := swing or switchSmall
    downSmall := down

// if(switchLarge and not downLarge)
//     alert("ALERT; type-Large Swing Low, time-" + formattedTime, alert.freq_once_per_bar_close)
// if(switchLarge and downLarge)
//     alert("ALERT; type-Large Swing High, time-" + formattedTime, alert.freq_once_per_bar_close)
// if(switchMedium and not downMedium)
//     alert("ALERT; type-Medium Swing Low, time-" + formattedTime, alert.freq_once_per_bar_close)
// if(switchMedium and downMedium)
//     alert("ALERT; type-Medium Swing High, time-" + formattedTime, alert.freq_once_per_bar_close)
// if(switchSmall and not downSmall)
//     alert("ALERT; type-Small Swing Low, time-" + formattedTime, alert.freq_once_per_bar_close)
// if(switchSmall and downSmall)
//     alert("ALERT; type-Small Swing High, time-" + formattedTime, alert.freq_once_per_bar_close)

// alertcondition(switchLarge and not downLarge, 'Large Swing Low', 'Large Swing Low')
// alertcondition(switchLarge and downLarge, 'Large Swing High', 'Large Swing High')
// alertcondition(switchMedium and not downMedium, 'Medium Swing Low', 'Medium Swing Low')
// alertcondition(switchMedium and downMedium, 'Medium Swing High', 'Medium Swing High')
// alertcondition(switchSmall and not downSmall, 'Small Swing Low', 'Small Swing Low')
// alertcondition(switchSmall and downSmall, 'Small Swing High', 'Small Swing High')